from PyPDF2 import PdfMerger

# List of PDF file names
pdf_files = [
    "Utility-First Fundamentals.pdf",
    "Handling Hover, Focus, and Other States.pdf",
    "Responsive Design.pdf",
    "Dark Mode.pdf",
    "Reusing Styles.pdf",
    "Adding Custom Styles.pdf",
    "Functions & Directives.pdf",
    "Configuration.pdf",
    "Content Configuration.pdf",
    "Theme Configuration.pdf",
    "Customizing Screens.pdf",
    "Customizing Colors.pdf",
    "Customizing Spacing.pdf",
    "Plugins.pdf",
    "Presets.pdf",
    "Preflight.pdf",
    "Aspect Ratio.pdf",
    "Container.pdf",
    "Columns.pdf",
    "Break After.pdf",
    "Break Before.pdf",
    "Break Inside.pdf",
    "Box Decoration Break.pdf",
    "Box Sizing.pdf",
    "Display.pdf",
    "Floats.pdf",
    "Clear.pdf",
    "Isolation.pdf",
    "Object Fit.pdf",
    "Object Position.pdf",
    "Overflow.pdf",
    "Overscroll Behavior.pdf",
    "Position.pdf",
    "Top__Right__Bottom__Left.pdf",
    "Visibility.pdf",
    "Z-Index.pdf",
    "Flex_Basis.pdf",
    "Flex_Direction.pdf",
    "Flex_Wrap.pdf",
    "Flex.pdf",
    "Flex_Grow.pdf",
    "Flex_Shrink.pdf",
    "Order.pdf",
    "Grid_Template_Columns.pdf",
    "Grid_Column_Start__End.pdf",
    "Grid_Template_Rows.pdf",
    "Grid_Row_Start__End.pdf",
    "Grid_Auto_Flow.pdf",
    "Grid_Auto_Columns.pdf",
    "Grid_Auto_Rows.pdf",
    "Gap.pdf",
    "Justify_Content.pdf",
    "Justify_Items.pdf",
    "Justify_Self.pdf",
    "Align_Content.pdf",
    "Align_Items.pdf",
    "Align_Self.pdf",
    "Place_Content.pdf",
    "Place_Items.pdf",
    "Place_Self.pdf",
    "Padding.pdf",
    "Margin.pdf",
    "Space_Between.pdf",
    "Width.pdf",
    "Min-Width.pdf",
    "Max-Width.pdf",
    "Height.pdf",
    "Min-Height.pdf",
    "Max-Height.pdf",
    "Font_Family.pdf",
    "Font_Size.pdf",
    "Font_Smoothing.pdf",
    "Font_Style.pdf",
    "Font_Weight.pdf",
    "Font_Variant_Numeric.pdf",
    "Letter_Spacing.pdf",
    "Line_Clamp.pdf",
    "Line_Height.pdf",
    "List_Style_Image.pdf",
    "List_Style_Position.pdf",
    "List_Style_Type.pdf",
    "Text_Align.pdf",
    "Text_Color.pdf",
    "Text_Decoration.pdf",
    "Text_Decoration_Color.pdf",
    "Text_Decoration_Style.pdf",
    "Text_Decoration_Thickness.pdf",
    "Text_Underline_Offset.pdf",
    "Text_Transform.pdf",
    "Text_Overflow.pdf",
    "Text_Indent.pdf",
    "Vertical_Align.pdf",
    "Whitespace.pdf",
    "Word_Break.pdf",
    "Hyphens.pdf",
    "Content.pdf",
    "Background_Attachment.pdf",
    "Background_Clip.pdf",
    "Background_Color.pdf",
    "Background_Origin.pdf",
    "Background_Position.pdf",
    "Background_Repeat.pdf",
    "Background_Size.pdf",
    "Background_Image.pdf",
    "Gradient_Color_Stops.pdf",
    "Border_Radius.pdf",
    "Border_Width.pdf",
    "Border_Color.pdf",
    "Border_Style.pdf",
    "Divide_Width.pdf",
    "Divide_Color.pdf",
    "Divide_Style.pdf",
    "Outline_Width.pdf",
    "Outline_Color.pdf",
    "Outline_Style.pdf",
    "Outline_Offset.pdf",
    "Ring_Width.pdf",
    "Ring_Color.pdf",
    "Ring_Offset_Width.pdf",
    "Ring_Offset_Color.pdf",
    "Box_Shadow.pdf",
    "Box_Shadow_Color.pdf",
    "Opacity.pdf",
    "Mix_Blend_Mode.pdf",
    "Background_Blend_Mode.pdf",
    "Blur.pdf",
    "Brightness.pdf",
    "Contrast.pdf",
    "Drop_Shadow.pdf",
    "Grayscale.pdf",
    "Hue_Rotate.pdf",
    "Invert.pdf",
    "Saturate.pdf",
    "Sepia.pdf",
    "Backdrop_Blur.pdf",
    "Backdrop_Brightness.pdf",
    "Backdrop_Contrast.pdf",
    "Backdrop_Grayscale.pdf",
    "Backdrop_Hue_Rotate.pdf",
    "Backdrop_Invert.pdf",
    "Backdrop_Opacity.pdf",
    "Backdrop_Saturate.pdf",
    "Backdrop_Sepia.pdf",
    "Border_Collapse.pdf",
    "Border_Spacing.pdf",
    "Table_Layout.pdf",
    "Caption_Side.pdf",
    "Transition_Property.pdf",
    "Transition_Duration.pdf",
    "Transition_Timing_Function.pdf",
    "Transition_Delay.pdf",
    "Animation.pdf",
    "Scale.pdf",
    "Rotate.pdf",
    "Translate.pdf",
    "Skew.pdf",
    "Transform_Origin.pdf",
    "Accent_Color.pdf",
    "Appearance.pdf",
    "Cursor.pdf",
    "Caret_Color.pdf",
    "Pointer_Events.pdf",
    "Resize.pdf",
    "Scroll_Behavior.pdf",
    "Scroll_Margin.pdf",
    "Scroll_Padding.pdf",
    "Scroll_Snap_Align.pdf",
    "Scroll_Snap_Stop.pdf",
    "Scroll_Snap_Type.pdf",
    "Touch_Action.pdf",
    "User_Select.pdf",
    "Will_Change.pdf",
    "Fill.pdf",
    "Stroke.pdf",
    "Stroke_Width.pdf",
    "Screen_Readers.pdf",
    "tailwindcsstypography.pdf"
]

# Output PDF file
output_pdf = "tailwindDocs.pdf"

# Create a PDF merger object
merger = PdfMerger()

# Merge the PDF files
for pdf_file in pdf_files:
    merger.append(pdf_file)

# Save the merged PDF to the output file
merger.write(output_pdf)

# Close the merger
merger.close()

print(f"PDF files merged successfully. Combined PDF saved as '{output_pdf}'.")
