import os
import pdfkit
from PyPDF2 import PdfMerger, PdfWriter


# List of text file names
text_files = [
    "Utility-First Fundamentals.txt",
    "Handling Hover, Focus, and Other States.txt",
    "Responsive Design.txt",
    "Dark Mode.txt",
    "Reusing Styles.txt",
    "Adding Custom Styles.txt",
    "Functions & Directives.txt",
    "Configuration.txt",
    "Content Configuration.txt",
    "Theme Configuration.txt",
    "Customizing Screens.txt",
    "Customizing Colors.txt",
    "Customizing Spacing.txt",
    "Plugins.txt",
    "Presets.txt",
    "Preflight.txt",
    "Aspect Ratio.txt",
    "Container.txt",
    "Columns.txt",
    "Break After.txt",
    "Break Before.txt",
    "Break Inside.txt",
    "Box Decoration Break.txt",
    "Box Sizing.txt",
    "Display.txt",
    "Floats.txt",
    "Clear.txt",
    "Isolation.txt",
    "Object Fit.txt",
    "Object Position.txt",
    "Overflow.txt",
    "Overscroll Behavior.txt",
    "Position.txt",
    "Top__Right__Bottom__Left.txt",
    "Visibility.txt",
    "Z-Index.txt",
    "Flex_Basis.txt",
    "Flex_Direction.txt",
    "Flex_Wrap.txt",
    "Flex.txt",
    "Flex_Grow.txt",
    "Flex_Shrink.txt",
    "Order.txt",
    "Grid_Template_Columns.txt",
    "Grid_Column_Start__End.txt",
    "Grid_Template_Rows.txt",
    "Grid_Row_Start__End.txt",
    "Grid_Auto_Flow.txt",
    "Grid_Auto_Columns.txt",
    "Grid_Auto_Rows.txt",
    "Gap.txt",
    "Justify_Content.txt",
    "Justify_Items.txt",
    "Justify_Self.txt",
    "Align_Content.txt",
    "Align_Items.txt",
    "Align_Self.txt",
    "Place_Content.txt",
    "Place_Items.txt",
    "Place_Self.txt",
    "Padding.txt",
    "Margin.txt",
    "Space_Between.txt",
    "Width.txt",
    "Min-Width.txt",
    "Max-Width.txt",
    "Height.txt",
    "Min-Height.txt",
    "Max-Height.txt",
    "Font_Family.txt",
    "Font_Size.txt",
    "Font_Smoothing.txt",
    "Font_Style.txt",
    "Font_Weight.txt",
    "Font_Variant_Numeric.txt",
    "Letter_Spacing.txt",
    "Line_Clamp.txt",
    "Line_Height.txt",
    "List_Style_Image.txt",
    "List_Style_Position.txt",
    "List_Style_Type.txt",
    "Text_Align.txt",
    "Text_Color.txt",
    "Text_Decoration.txt",
    "Text_Decoration_Color.txt",
    "Text_Decoration_Style.txt",
    "Text_Decoration_Thickness.txt",
    "Text_Underline_Offset.txt",
    "Text_Transform.txt",
    "Text_Overflow.txt",
    "Text_Indent.txt",
    "Vertical_Align.txt",
    "Whitespace.txt",
    "Word_Break.txt",
    "Hyphens.txt",
    "Content.txt",
    "Background_Attachment.txt",
    "Background_Clip.txt",
    "Background_Color.txt",
    "Background_Origin.txt",
    "Background_Position.txt",
    "Background_Repeat.txt",
    "Background_Size.txt",
    "Background_Image.txt",
    "Gradient_Color_Stops.txt",
    "Border_Radius.txt",
    "Border_Width.txt",
    "Border_Color.txt",
    "Border_Style.txt",
    "Divide_Width.txt",
    "Divide_Color.txt",
    "Divide_Style.txt",
    "Outline_Width.txt",
    "Outline_Color.txt",
    "Outline_Style.txt",
    "Outline_Offset.txt",
    "Ring_Width.txt",
    "Ring_Color.txt",
    "Ring_Offset_Width.txt",
    "Ring_Offset_Color.txt",
    "Box_Shadow.txt",
    "Box_Shadow_Color.txt",
    "Opacity.txt",
    "Mix_Blend_Mode.txt",
    "Background_Blend_Mode.txt",
    "Blur.txt",
    "Brightness.txt",
    "Contrast.txt",
    "Drop_Shadow.txt",
    "Grayscale.txt",
    "Hue_Rotate.txt",
    "Invert.txt",
    "Saturate.txt",
    "Sepia.txt",
    "Backdrop_Blur.txt",
    "Backdrop_Brightness.txt",
    "Backdrop_Contrast.txt",
    "Backdrop_Grayscale.txt",
    "Backdrop_Hue_Rotate.txt",
    "Backdrop_Invert.txt",
    "Backdrop_Opacity.txt",
    "Backdrop_Saturate.txt",
    "Backdrop_Sepia.txt",
    "Border_Collapse.txt",
    "Border_Spacing.txt",
    "Table_Layout.txt",
    "Caption_Side.txt",
    "Transition_Property.txt",
    "Transition_Duration.txt",
    "Transition_Timing_Function.txt",
    "Transition_Delay.txt",
    "Animation.txt",
    "Scale.txt",
    "Rotate.txt",
    "Translate.txt",
    "Skew.txt",
    "Transform_Origin.txt",
    "Accent_Color.txt",
    "Appearance.txt",
    "Cursor.txt",
    "Caret_Color.txt",
    "Pointer_Events.txt",
    "Resize.txt",
    "Scroll_Behavior.txt",
    "Scroll_Margin.txt",
    "Scroll_Padding.txt",
    "Scroll_Snap_Align.txt",
    "Scroll_Snap_Stop.txt",
    "Scroll_Snap_Type.txt",
    "Touch_Action.txt",
    "User_Select.txt",
    "Will_Change.txt",
    "Fill.txt",
    "Stroke.txt",
    "Stroke_Width.txt",
    "Screen_Readers.txt",
    "tailwindcsstypography.txt"
]

# Convert each text file to PDF
for text_file in text_files:
    pdf_file = text_file.replace(".txt", ".pdf")
    pdfkit.from_file(text_file, pdf_file)
    print(f"PDF file '{pdf_file}' created successfully.")


